# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5699cd48a9bc4e17048fec507b1acc6c925dab6c88616d1bd0487f1be6a44e6c8b4c4b8bcec274e097a9ba9c76ee9479c1f304ecbe1f4315efb6a20423f20e89

test:
  secret_key_base: 84681fd61f023ccb1bccc5dd41610c8ecac965e03c4f1d23d754f2e60e748aa38afab1bb43f10c1e19f0d86201d76031745e1c94384ad14ea0f6cfa97f060644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
